import {
  defineNuxtModule,
  addPlugin,
  createResolver,
  addTemplate,
  extendViteConfig,
  addImports
} from '@nuxt/kit'
import { addCustomTab } from '@nuxt/devtools-kit'
import { name, version } from '../package.json'
import type { NuxtUIkitModuleOptions } from './types'

export default defineNuxtModule<NuxtUIkitModuleOptions>({
  meta: {
    name,
    version,
    configKey: 'uikit3',
    compatibility: {
      nuxt: '^3.0.0',
      bridge: false
    }
  },
  defaults: {
    css: {
      coreCss: true,
      coreTheme: true
    },
    js: true,
    icons: true
  },
  setup: function (moduleOpts, nuxt) {
    const resolver = createResolver(import.meta.url)

    const nuxtOptions = nuxt.options

    // @ts-ignore
    nuxtOptions.runtimeConfig.public.uikit ||= {} as NuxtUIkitModuleOptions
    // @ts-ignore
    nuxtOptions.runtimeConfig.public.uikit = moduleOpts

    const cssOptions = moduleOpts.css
    // load only core css
    if (cssOptions?.coreCss && !cssOptions.coreTheme) {
      nuxtOptions.css ||= []
      nuxtOptions.css.push(`uikit/dist/css/uikit-core.min.css`)
    }
    // load core + default theme css
    if (cssOptions?.coreCss && cssOptions.coreTheme) {
      nuxtOptions.css ||= []
      nuxtOptions.css.push(`uikit/dist/css/uikit.min.css`)
    }
    // custom css build
    if (cssOptions?.build) {
      nuxtOptions.vite ||= {}
      nuxtOptions.vite.css ||= {}
      nuxtOptions.vite.css.preprocessorOptions ||= {}

      // main stylesheet
      nuxtOptions.css ||= []
      nuxtOptions.css.push(moduleOpts?.css?.build?.stylesPath || '')

      const lang = cssOptions.build.preprocessor
      if (lang === 'scss') {
        if (cssOptions.build.variablesPath) {
          nuxtOptions.vite.css.preprocessorOptions.scss = {
            additionalData: `@import "${moduleOpts?.css?.build?.variablesPath}";`
          }
        }
        if (cssOptions.build.mixinsPath) {
          nuxtOptions.vite.css.preprocessorOptions.scss = {
            additionalData: `@import "${moduleOpts?.css?.build?.mixinsPath}";`
          }
        }
      } else if (lang === 'less') {
        if (cssOptions.build.variablesPath) {
          nuxtOptions.vite.css.preprocessorOptions.less = {
            additionalData: `@import "${moduleOpts?.css?.build?.variablesPath}";`
          }
        }
        if (cssOptions.build.mixinsPath) {
          nuxtOptions.vite.css.preprocessorOptions.less = {
            additionalData: `@import "${moduleOpts?.css?.build?.mixinsPath}";`
          }
        }
      }
    }

    if (moduleOpts.js) {
      addPlugin({
        src: resolver.resolve('runtime/plugin'),
        mode: 'client'
      })

      addImports({
        name: 'useUIkit3',
        as: 'useUIkit3',
        from: resolver.resolve('runtime/composables/useUIkit3')
      })

      nuxtOptions.build.transpile ||= []
      nuxtOptions.build.transpile.push('uikit')

      extendViteConfig((config) => {
        config.optimizeDeps = config.optimizeDeps || {}
        config.optimizeDeps.include = config.optimizeDeps.include || []
        config.optimizeDeps.include.push('uikit')
      })

      if (moduleOpts.icons) {
        nuxtOptions.build.transpile ||= []
        nuxtOptions.build.transpile.push('uikit/dist/js/uikit-icons')

        extendViteConfig((config) => {
          config.optimizeDeps = config.optimizeDeps || {}
          config.optimizeDeps.include = config.optimizeDeps.include || []
          config.optimizeDeps.include.push('uikit/dist/js/uikit-icons')
        })
      }
    }

    // add uikit documentation to DevTools
    if (nuxt.options.dev && nuxt.options.devtools) {
      addCustomTab({
        name: 'nuxt-uikit3',
        title: 'UIkit 3',
        icon: 'logos:uikit',
        view: {
          type: 'iframe',
          src: 'https://getuikit.com/docs/introduction'
        }
      })
    }

    // add uikit types
    addTemplate({
      filename: 'types/nuxt-uikit3.d.ts',
      getContents: () => `// Generated by nuxt-uikit3
        import type UIkit from 'uikit'

        declare module '#app' {
          interface NuxtApp {
            $uikit3: UIkit;
          }
        }
        declare module '@vue/runtime-core' {
          interface ComponentCustomProperties {
            $uikit3: UIkit;
          }
        }
        export {}`
    })
  }
})
